from copy import deepcopy
RANK_RANDOM='rank_random'; RANDOM3_PICK1='random3_pick1'; TACTICAL_BO3='tactical_bo3'; BO3='bo3'; BAN_PICK_BO3='ban_pick_bo3'; HOME_AWAY='home_away'
MODE_ORDER=(RANK_RANDOM,RANDOM3_PICK1,TACTICAL_BO3,BO3,BAN_PICK_BO3,HOME_AWAY)
DEFAULT_MODE_CONFIGS={
RANK_RANDOM:{'code':RANK_RANDOM,'label':'Rank thường Random','short_label':'Random','enabled':True,'min_rp':0,'min_matches':0,'max_rp_gap':0,'series_type':'single','max_games':1,'club_method':'random_one','rp':{'formula':'rank_current'}},
RANDOM3_PICK1:{'code':RANDOM3_PICK1,'label':'Random 3 chọn 1','short_label':'3 chọn 1','enabled':True,'min_rp':0,'min_matches':5,'max_rp_gap':0,'series_type':'single','max_games':1,'club_method':'secret_pick_three','rp':{'formula':'rank_current'}},
TACTICAL_BO3:{'code':TACTICAL_BO3,'label':'Đấu chiến thuật BO3','short_label':'Chiến thuật BO3','enabled':True,'min_rp':1500,'min_matches':20,'max_rp_gap':500,'series_type':'best_of','wins_required':2,'max_games':3,'club_method':'secret_pick_three_no_reuse','rp':{'win_2_0':40,'lose_0_2':-28,'win_2_1':34,'lose_1_2':-24,'forfeit_win':34,'forfeit_loss':-32,'draw_1_1':3,'draw_all':2}},
BO3:{'code':BO3,'label':'BO3','short_label':'BO3','enabled':True,'min_rp':1300,'min_matches':15,'max_rp_gap':500,'series_type':'best_of','wins_required':2,'max_games':3,'club_method':'tier_random_each_game','rp':{'win_2_0':40,'lose_0_2':-28,'win_2_1':34,'lose_1_2':-24,'forfeit_win':34,'forfeit_loss':-32,'draw_1_1':3,'draw_all':2}},
BAN_PICK_BO3:{'code':BAN_PICK_BO3,'label':'Cấm chọn CLB BO3','short_label':'Cấm chọn BO3','enabled':True,'min_rp':1500,'min_matches':20,'max_rp_gap':500,'series_type':'best_of','wins_required':2,'max_games':3,'club_method':'shared_pool_ban_pick_no_reuse','pool_size':20,'bans_per_player':3,'ban_seconds':30,'pick_seconds':30,'rp':{'win_2_0':42,'lose_0_2':-29,'win_2_1':36,'lose_1_2':-25,'forfeit_win':35,'forfeit_loss':-33,'draw_1_1':3,'draw_all':2}},
HOME_AWAY:{'code':HOME_AWAY,'label':'Lượt đi – lượt về','short_label':'Lượt đi/về','enabled':True,'min_rp':1200,'min_matches':10,'max_rp_gap':500,'series_type':'aggregate_two_legs','max_games':2,'club_method':'change_or_swap_by_admin','away_goals':False,'rp':{'one_win_one_draw_win':25,'one_win_one_draw_loss':-21,'win_both':29,'lose_both':-23,'draw':3,'forfeit_win':25,'forfeit_loss':-30}},}
def default_mode_configs(): return deepcopy(DEFAULT_MODE_CONFIGS)
